ASP2236903/Models/producto_imagen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP2236903.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto_imagen
    {
        public int id { get; set; }
        public string imagen { get; set; }
        public int id_producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}

ASP2236903/Controllers/ProductoImagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using ASP2236903.Models;

namespace ASP2236903.Controllers
{
    public class ProductoImagenController : Controller
    {
        // GET: ProductoImagen
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CargarImagen(int producto, HttpPostedFileBase imagen)
        {
            try {
                //string para guardar la ruta
                string filePath = string.Empty;
                string nameFile = "";

                //condicion para saber si el archivo llego
                if (imagen != null)
                {
                    //ruta de la carpeta que guardara el archivo
                    string path = Server.MapPath("~/Uploads/Imagenes/");

                    //condicion para saber si la carpeta uploads existe
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    nameFile = Path.GetFileName(imagen.FileName);

                    //obtener el nombre del archivo
                    filePath = path + Path.GetFileName(imagen.FileName);

                    //obtener la extension del archivo
                    string extension = Path.GetExtension(imagen.FileName);

                    //guardar el archivo
                    imagen.SaveAs(filePath);
                }

                using (var db = new inventario2021Entities())
                {
                    var imagenProducto = new producto_imagen();
                    imagenProducto.id_producto = producto;
                    imagenProducto.imagen = "/Uploads/Imagenes/" + nameFile;
                    db.producto_imagen.Add(imagenProducto);
                    db.SaveChanges();

                }

                return View();

            }
            catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
            
        }
    }
}

ASP2236903/Views/ProductoImagen/CargarImagen.cshtml
<h2>Cargar Imagen Producto</h2>

@using (Html.BeginForm("CargarImagen", "ProductoImagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        <label class="control-label col-md-2">Producto</label>
        <div class="col-md-10">
            <input type="number" name="producto" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Imagen</label>
        <div class="col-md-10">
            <input type="file" name="imagen" class="form-control" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-10">
            <input type="submit" value="Enviar" class="form-control" />
        </div>
    </div>

}