ASP2236903/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP2236903.Models;
using Rotativa;
using System.IO;
using ASP2236903.Filtros;

namespace ASP2236903.Controllers
{
    [Authorize]
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities())
            {
                return View(db.producto.ToList());
            }
                
        }

        public static string NombreProveedor(int idProveedor)
        {
            using (var db = new inventario2021Entities())
            {
                return db.proveedor.Find(idProveedor).nombre;
            }
        }

        public ActionResult ListarProveedores()
        {
            using (var db = new inventario2021Entities())
            {
                return PartialView(db.proveedor.ToList());
            }
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto producto)
        {
            if (!ModelState.IsValid)
                return View();

            try {
                using (var db = new inventario2021Entities())
                {
                    db.producto.Add(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities())
            {
                var producto = db.producto.Find(id);

                //conusltando de la tabla producto_iamgen las imagenes del producto
                var imagen = db.producto_imagen.Where(e => e.id_producto == producto.id).FirstOrDefault();
                //pasando la ruta a la vista
                ViewBag.imagen = imagen.imagen;

                return View(producto);
            }
        }

        public ActionResult Edit(int id)
        {
            using (var db = new inventario2021Entities())
            {
                producto productoEdit = db.producto.Where(a => a.id == id).FirstOrDefault();
                return View(productoEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto productoEdit)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    var oldProduct = db.producto.Find(productoEdit.id);
                    oldProduct.nombre = productoEdit.nombre;
                    oldProduct.cantidad = productoEdit.cantidad;
                    oldProduct.descripcion = productoEdit.descripcion;
                    oldProduct.percio_unitario = productoEdit.percio_unitario;
                    oldProduct.id_proveedor = productoEdit.id_proveedor;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    producto producto = db.producto.Find(id);
                    db.producto.Remove(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Reporte()
        {
            try
            {
                var db = new inventario2021Entities();
                var query = from tabProveedor in db.proveedor
                            join tabProducto in db.producto on tabProveedor.id equals tabProducto.id_proveedor
                            select new Reporte
                            {
                                nombreProveedor = tabProveedor.nombre,
                                telefonoProveedor = tabProveedor.telefono,
                                direccionProveedor = tabProveedor.direccion,
                                nombreProducto = tabProducto.nombre,
                                PrecioProducto = tabProducto.percio_unitario
                            };
                return View(query);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult PdfReporte()
        {
            return new ActionAsPdf("Index") { FileName = "reporte.pdf" };
        }

        [AuthorizeUser(idRol: 1)]
        public ActionResult cargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult cargarImagen(int producto, HttpPostedFileBase fileForm)
        {
            //string para guardar la ruta
            string filePath = string.Empty;
            string name = "";

            //condicion para saber si el archivo llego
            if (fileForm != null)
            {
                //ruta de la carpeta que guardara el archivo
                string path = Server.MapPath("~/Uploads/Imagenes/");

                //condicion para saber si la carpeta uploads existe
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                name = Path.GetFileName(fileForm.FileName);
                //obtener el nombre del archivo
                filePath = path + Path.GetFileName(fileForm.FileName);

                //obtener la extension del archivo
                string extension = Path.GetExtension(fileForm.FileName);

                //guardar el archivo
                fileForm.SaveAs(filePath);

                
            }


            using (var db = new inventario2021Entities())
            {
                var imagenProducto = new producto_imagen();
                imagenProducto.id_producto = producto;
                imagenProducto.imagen = "/Uploads/Imagenes/" + name;
                db.producto_imagen.Add(imagenProducto);
                db.SaveChanges();
            }

                return View();
        }

    }
}

ASP2236903/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ASP2236903.Models;
using System.Web.Security;
using System.Text;
using System.Web.Security;
using System.Web.Routing;


namespace ASP2236903.Controllers
{
    public class UsuarioController : Controller
    {
        [Authorize]
        // GET: Usuario
        public ActionResult Index()
        {
            //conexion a la base de datos
            using (var db = new inventario2021Entities()) 
            { 
                return View(db.usuario.ToList());
            }  
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(usuario usuario)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var db = new inventario2021Entities())
                {
                    usuario.password = UsuarioController.HashSHA1(usuario.password);
                    db.usuario.Add(usuario);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public static string HashSHA1(string value)
        {
            var sha1 = System.Security.Cryptography.SHA1.Create();
            var inputBytes = Encoding.ASCII.GetBytes(value);
            var hash = sha1.ComputeHash(inputBytes);

            var sb = new StringBuilder();
            for ( var i = 0; i < hash.Length; i++)
            {
                sb.Append(hash[i].ToString("X2"));
            }
            return sb.ToString();
        }

        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities())
            {
                var findUser = db.usuario.Find(id);
                return View(findUser);
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    var findUser = db.usuario.Find(id);
                    db.usuario.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities())
                {
                    usuario findUser = db.usuario.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(usuario editUser)
        {
            try
            {

                using (var db = new inventario2021Entities())
                {
                    usuario user = db.usuario.Find(editUser.id);
                    
                    user.nombre = editUser.nombre;
                    user.apellido = editUser.apellido;
                    user.email = editUser.email;
                    user.fecha_nacimiento = editUser.fecha_nacimiento;
                    user.password = editUser.password;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Login(string mensaje = "")
        {
            ViewBag.Message = mensaje;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string user, string password)
        {
            try
            {
                string passEncrip = UsuarioController.HashSHA1(password);
                using (var db = new inventario2021Entities())
                {
                    var userLogin = db.usuario.FirstOrDefault(e => e.email == user && e.password == passEncrip);
                    if(userLogin != null)
                    {
                        FormsAuthentication.SetAuthCookie(userLogin.email, true);
                        Session["User"] = userLogin;
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        return Login("Verifique sus datos");
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        [Authorize]
        public ActionResult CloseSession()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult PaginadorIndex(int pagina = 1)
        {
            try
            {
                var cantidadRegistros = 5;

                using (var db = new inventario2021Entities())
                {
                    var usuarios = db.usuario.OrderBy(x => x.id).Skip((pagina - 1) * cantidadRegistros).Take(cantidadRegistros).ToList();

                    var totalRegistros = db.usuario.Count();
                    var modelo = new UsuarioIndex();
                    modelo.Usuarios = usuarios;
                    modelo.ActualPage = pagina;
                    modelo.Total = totalRegistros;
                    modelo.RecordsPage = cantidadRegistros;
                    modelo.valueQueryString = new RouteValueDictionary();

                    return View(modelo);
                }

            }catch(Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

    }
}

ASP2236903/Views/Shared/Paginador.cshtml
@model ASP2236903.Models.BaseModelo

@{ 
    var cantidadPaginas = (int)Math.Ceiling((double)Model.Total / Model.RecordsPage);
}

<ul>
    @if (Model.ActualPage == 1)
    {
        Model.valueQueryString["pagina"] = 1;
        <li class="disabled">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li>
    }
    else
    {
        Model.valueQueryString["pagina"] = Model.ActualPage - 1;
        <li class="">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li>
    }

    @if (Model.ActualPage == cantidadPaginas)
    {
        Model.valueQueryString["pagina"] = cantidadPaginas;
        <li class="disabled">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li>
    }
    else
    {
        Model.valueQueryString["pagina"] = Model.ActualPage + 1;
        <li class="">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li>
    }

</ul>

@{
    int Inicial = 1;
    var radio = 3;
    var cantidadMaximaDePaginas = radio * 2 - 1;
    int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;

    if (Model.ActualPage > radio + 1)
    {
        Inicial = Model.ActualPage - radio;

        if (cantidadPaginas > Model.ActualPage + radio)
        {
            Final = Model.ActualPage + radio;
        }
        else
        {
            Final = cantidadPaginas;
        }
    }

}

<ul class="pagination">
    @{Model.valueQueryString["pagina"] = 1; }

    <li>@Html.ActionLink("Primera", null, Model.valueQueryString)</li>
    @for (int i = Inicial; i <= Final; i++)
    {
        Model.valueQueryString["pagina"] = i;
        if (i == Model.ActualPage)
        {
            <li class="active">@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li>
        }
        else
        {
            <li>@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li>
        }
    }
    @{Model.valueQueryString["pagina"] = cantidadPaginas; }
    <li>@Html.ActionLink("Ultima", null, Model.valueQueryString)</li>
</ul>

ASP2236903/Views/Shared/Plantilla.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Plantilla - Nuevo Layout</title>
</head>
<body>
    <div>
        @RenderBody()

        <p>
            @RenderSection("textoParrafo", required: true)
        </p>
    </div>
</body>
</html>

ASP2236903/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/custom.css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Software Inventario", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Opciones
                            <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Usuario Crud", "Index", "Usuario")</li>
                            <li>@Html.ActionLink("Producto Crud", "Index", "Producto")</li>
                        </ul>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Cerrar Sesion", "CloseSession", "Usuario")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Dev by: Javier Ortegon</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>